### ISSUE TITLE
A problem that always arises

### ISSUE THREAD

**Issue by BingZi-233** [CloudNetService/CloudNet-v3#555]
Node-1 node IP: 192.168.21.10:1410
Node-2 node IP: 192.168.21.11:1410

Node-1 Info：
```yaml
CloudNet Earthquake 3.4.0-RELEASE-e62b24c by Dytanic & the CloudNet Community
Discord: https://discord.cloudnetservice.eu/
 
ClusterId: 59473520-b380-4f44-b371-e38b0bca3f22
NodeId: Node-1
Head-NodeId: Node-2
CPU usage: (P/S) 0/2.94/100%
Node services memory allocation (U/R/M): 512/512/2048 MB
Threads: 26
Heap usage: 62/456MB
Loaded classes: 5865
Unloaded classes: 0
Total loaded classes: 5865

```

Node-2 Info：
```yaml
CloudNet Earthquake 3.4.0-RELEASE-e62b24c by Dytanic & the CloudNet Community
Discord: https://discord.cloudnetservice.eu/
 
ClusterId: 59473520-b380-4f44-b371-e38b0bca3f22
NodeId: Node-2
Head-NodeId: Node-2
CPU usage: (P/S) 1.56/0/100%
Node services memory allocation (U/R/M): 0/0/2048 MB
Threads: 29
Heap usage: 134/456MB
Loaded classes: 5692
Unloaded classes: 85
Total loaded classes: 5777
```

MySQL info：
- host：192.168.21.1
- port：3306
- username：root
- password：135421

**Don't worry, all content is for intranet access only. It has not opened up to the public network.**

Error Info：
```java
[11.10 21:41:53.885] ERROR: java.lang.ArrayIndexOutOfBoundsException: Index 49 out of bounds for length 3
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.serialization.DefaultProtocolBuffer.readEnumConstant(DefaultProtocolBuffer.java:345)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.channel.ChannelMessageSender.read(ChannelMessageSender.java:74)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.serialization.DefaultProtocolBuffer.readObject(DefaultProtocolBuffer.java:261)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.serialization.DefaultProtocolBuffer.readObject(DefaultProtocolBuffer.java:253)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.channel.ChannelMessage.read(ChannelMessage.java:136)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.serialization.DefaultProtocolBuffer.readObject(DefaultProtocolBuffer.java:261)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.serialization.DefaultProtocolBuffer.readObjectCollection(DefaultProtocolBuffer.java:298)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.provider.NodeMessenger.lambda$sendChannelMessageQueryAsync$3(NodeMessenger.java:244)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.common.concurrent.ITask.lambda$onComplete$0(ITask.java:55)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.common.concurrent.ITask$1.onComplete(ITask.java:48)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.common.concurrent.CompletableTask.complete(CompletableTask.java:157)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.network.def.internal.InternalSyncPacketChannel.lambda$registerQueryHandler$2(InternalSyncPacketChannel.java:86)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.network.def.internal.InternalSyncPacketChannel.handleIncomingChannel(InternalSyncPacketChannel.java:50)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.network.NetworkClientChannelHandlerImpl.handlePacketReceive(NetworkClientChannelHandlerImpl.java:60)
[11.10 21:41:53.886] ERROR:     at de.dytanic.cloudnet.driver.network.netty.NettyNetworkHandler.lambda$channelRead0$0(NettyNetworkHandler.java:66)
[11.10 21:41:53.886] ERROR:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[11.10 21:41:53.886] ERROR:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[11.10 21:41:53.886] ERROR:     at java.base/java.lang.Thread.run(Thread.java:829)
```
